---
name: CGI-Application-Plugin-CHI
version: 0.01
author:
  - 'Mike Friedman <friedo@friedo.com>'
abstract: CGI-App plugin for CHI caching interface
license: perl
requires:
  CGI::Application: 0
  CHI: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  CGI::Application::Plugin::CHI:
    file: lib/CGI/Application/Plugin/CHI.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
