---
name: CGI-Application-Plugin-CHI
version: 0.03
author:
  - 'Mike Friedman <friedo@friedo.com>'
abstract: CGI-App plugin for CHI caching interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  CGI::Application: 0
  CHI: 0
  Scalar::Util: 0
configure_requires:
  Module::Build: 0.35
provides:
  CGI::Application::Plugin::CHI:
    file: lib/CGI/Application/Plugin/CHI.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
